### PR TITLE
002 create database model

### PR DESCRIPTION
**Pull request by MaciejIwan**
image

### CODE REVIEW

**Comment by Rozumek29** [comment]
I would change the name of foler from entity to dto

**Comment by pacion** [comment]
⚔Last time we talked with Kasia about the app's **location** problem (which had to be worldwide). We decided to stay with Poland - merging all the stuff on the map with whole Europe will be much harder to achieve for them.

⚔I would suggest you to make new table called something like yhmm **role_table**? So we can put relation between user_model and **role_table**. It will give us possibility to add new roles without any extra modifications in the db model.
      ROLE
ID          NAME
1           USER_ROLE
2           ADMIN_ROLE
3           ROOT_ROLE

In addition the problem with string vs int vs enum I think is solved.

⚔ There is a "status" in user_model. I understand it like it is active, blocked (banned by admin) etc. So the way to make it is same as the one with roles.
      STATUS
ID          NAME
1           ACTIVE
2           BLOCKED

⚔Need logo_url for user as well.

⚔Kasia told us we need to have space for user's current university so in the comments she can provide showing the user's university she is currently in.

btw good idea with the background_photo_url

⚔ What about changing author_id into user_id? Looking at author_id and understanding the model took me a while.

⚔ user_model into user or app_user?

⚔ reviews_id into review_id?

⚔review.stars -> review.rating

⚔review.type -> review.name

Haven't checked the code yet.

**Comment by MaciejIwan** [comment]
image
New database diagram

**Review by pacion — APPROVED** [review]
lgtm
don't merge i do it tomorrow

**Pull request closed without merging**
